name: Periodic Check
on:
  schedule:
    - cron:  '31 1,12 * * *'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Latest V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout VTL
      uses: actions/checkout@v2
      with:
        path: vtl
    - name: Build V
      run: |
        make
        sudo ./v symlink
    - name: V doctor
      run: v doctor
    - name: Install VTL dependencies
      run: |
        sudo apt-get install --quiet -y --no-install-recommends gfortran liblapacke-dev libopenblas-dev
        v install vsl
    - name: run tests
      run: cd vtl; make test
